services:
  postgres:
    image: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Change to your email
      PGADMIN_DEFAULT_PASSWORD: admin # Change the password
    ports:
      - "9090:80"
    depends_on:
      - postgres
    networks:
      - pg_network

  api:
    build: .
    container_name: node_api
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/mydatabase?schema=public"
      JWT_SECRET: "your_secret_key"
    networks:
      - pg_network

volumes:
  pg_data:

networks:
  pg_network:
    driver: bridge
