version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Change to your email
      PGADMIN_DEFAULT_PASSWORD: admin # Change the password
    ports:
      - "8080:80" # Change to port 8080 to avoid conflict with port 80
    depends_on:
      - postgres
    networks:
      - pg_network

volumes:
  pg_data:

networks:
  pg_network:
    driver: bridge
